# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: perfectman0219@gmail.com
GMAIL_PASSWORD: saint840123
ADMIN_NAME: admin
ADMIN_EMAIL: admin@admin.com
ADMIN_PASSWORD: adminadmin

s3_bucket: budget247-bucket
s3_access_key_id: AKIAJENAE6WFXJ2RIMYQ
s3_secret_access_key: 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
s3_dir: 'dev'